apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: mlops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::471932414173:role/mlflow-s3-access
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: mlops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::471932414173:role/fraud-api-s3-readonly
