apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-secret
  namespace: mlops
type: Opaque
stringData:
  DB_USERNAME: "<injected by CI>"
  DB_PASSWORD: "<injected by CI>"
  DB_NAME: "<injected by CI>"
  DB_HOST: "<injected by CI>"