apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlops
data:
  S3_BUCKET: "my-mlflow-bucket67678"
  ARTIFACT_ROOT_PREFIX: "artifacts"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-api-config
  namespace: mlops
data:
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  AWS_DEFAULT_REGION: "ap-south-1"
  MODEL_URI: "models:/FraudDetector/Production"