apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-api-monitor
  namespace: mlops
spec:
  selector:
    matchLabels:
      app: fraud-api-cloud
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - mlops